### ISSUE TITLE
Information on portage homepage regarding migration?

### ISSUE THREAD

**Issue by jasonbrodeur** [ualbertalib/DMPonline_v4#102]
Good morning, I had a researcher/administrator at my institution write me today asking the following questions about the legitimacy of the notification email that was sent overnight to all Portage users: 

" Do know if this email message is legitimate. From the Portage Network? See below.  I went to their website on my own and I didn’t see any message….. I’m cautious….. I wasn’t even able to find a place to ask them "

Given this feedback, I wonder if it might be worthwhile to include a short banner message providing information about the transition.

Thanks,
Jay

**Comment by weiweishi** [comment]
This is no longer needed - and we will look into an easier way to post to homepage for notification.
