### ISSUE TITLE
links issues related to changing of domain name

### ISSUE THREAD

**Issue by mhvezina** [ualbertalib/DMPonline_v4#103]
This problem is related to the recent changing of domain name:

While trying to change my forgotten password for DMP Assistant, I did receive an email with the

« Réinitialiser mon mot de passe » link  pointing towards => https://portagenetwork.ca/fr/users/password/edit?reset_password_token=(token_number)

I guess it should be changed for :

https://**assistant**.portagenetwork.ca/fr/users/password/edit?reset_password_token=(token_number) 

***

I also see a couple of ‘https://reseauportage.ca’ and 'http://portagenetwork.ca/fr' within fr.yml file (and I guess equivalent in en.yml ?) that probably should be changed for "assistant.portagenetwork.ca/fr"...

Maybe other variables should be looked at too ? (e.g.: invitation_link within email messages , etc.)

**Comment by weiweishi** [comment]
Thanks Marie Helene. I will look into that right now.

Weiwei

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by weiweishi** [comment]
This should be addressed with the latest change, and changes we made on the system through ansible playbook couple of weeks ago
