### ISSUE TITLE
French translation needed 

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/DMPonline_v4#105]
in config/locales/en.yml:

sign_up_text: "New to DMP Assistant? Sign up today <a href='auth/shibboleth'>with your institutional credentials</a>, or with the email registration form.

by_theme_or_by_question: "This guidance will apply:"

template_delete_message: "You are about to delete '%{template_title}'. Are you sure?"
template_destroyed_message: "Template was successfully deleted."

@mhvezina could you please help?

**Comment by mhvezina** [comment]
Hi @weiweishi 
See PR #106 
Anything else I can do for you?

**Comment by mhvezina** [comment]
@weiweishi 

I guess this issue can be closed now as all snippets of text were translated and integrated to main code. thank you.
