### ISSUE TITLE
Export -> text format : text variable (helpers.plan.export.pdf.question_not_answered) not recognized 

### ISSUE THREAD

**Issue by mhvezina** [ualbertalib/DMPonline_v4#108]
In the Export tab/section 

When chosing "text format" I get unresolved/unrecognized strings "I18n.t('helpers.plan.export.pdf.question_not_answered')}" showing where it should be written "Question not answered".

**Comment by astrilet** [comment]
simple fix in exported_plan.rb
Before and after Images
![screenshot from 2017-07-13 13-54-36](https://user-images.githubusercontent.com/11414991/28185038-122363e8-67d3-11e7-9014-f6d7135ec50c.png)
![screenshot from 2017-07-13 13-54-58](https://user-images.githubusercontent.com/11414991/28185045-1481d926-67d3-11e7-954e-a4c1c618133d.png)
