### ISSUE TITLE
Guidance list issue

### ISSUE THREAD

**Issue by bretonc** [ualbertalib/DMPonline_v4#110]
Hello. 
I am currently trying to add institutional guidance text (for University of Guelph) to the portage standard template. When I attempt to create a Guidance Group, I am not seeing the Portage Template in the template list only 'All Template'. When I attempt to create a Guidance List, an error message of 'We're sorry, something went wrong' appears.
Thanks
Carrie

**Comment by weiweishi** [comment]
Fixed with data change in the backend.
