### ISSUE TITLE
Guidance is visible even it's set to be not published. 

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/DMPonline_v4#118]
Reported by UQAM:

1.
![image](https://user-images.githubusercontent.com/2047614/28326337-ba2a664a-6b9d-11e7-89a4-b3b12c4b91e8.png)

 
2. Plans created in English and in French

 
![image](https://user-images.githubusercontent.com/2047614/28326351-c14e600c-6b9d-11e7-8b1b-1b0b12bdd9e0.png)

 
 
3. Display
![image](https://user-images.githubusercontent.com/2047614/28326360-cc0c8c12-6b9d-11e7-8fc6-ea524f57396c.png)

**Comment by weiweishi** [comment]
I can't reproduce this issue and I will contact the person who submitted this issue. @astrilet Could you please test if the guidance will always be available the person who has created it, even it's not published?

**Comment by astrilet** [comment]
Fixed, 
created group QQQ, unpublished, still was able to see it in plan questions:
![qqq-appearing](https://user-images.githubusercontent.com/11414991/28535322-2b7755d4-7061-11e7-98a8-2d96a878c4f2.png)
After the fix, it is not longer there
![qqq-not-appearing](https://user-images.githubusercontent.com/11414991/28535335-381aff70-7061-11e7-87e9-adc24d0d9025.png)

**Comment by astrilet** [comment]
make QQQ guidance group published
![guidance-published](https://user-images.githubusercontent.com/11414991/28536569-429b4f3c-7065-11e7-9872-856f4e8a9392.png)
QQQ guidance appearing again
![qqq-appearing-again](https://user-images.githubusercontent.com/11414991/28536591-52d254cc-7065-11e7-9c90-f80e702bb1cc.png)

**Comment by astrilet** [comment]
this issue has been fixed in PR #122
