### ISSUE TITLE
French interface for admin area throws an error

### ISSUE THREAD

**Issue by mhvezina** [ualbertalib/DMPonline_v4#127]
I get a “We're sorry, but something went wrong.” error when I click on the Admin area while using the French interface. I don't get an error with the English interface:

![portage_ok_admin_interface_english_only](https://user-images.githubusercontent.com/10760472/28781556-767bc624-75d8-11e7-99e7-cfc244f47b36.png)

**Comment by astrilet** [comment]
Could not reproduce it in development environment.

**Comment by mhvezina** [comment]
Issue still pending in the production environment (https://assistant.portagenetwork.ca) : is that normal?

**Comment by astrilet** [comment]
We have not migrated that change to the production yet, production team is busy. We tried to migrate it once but there were some issues, so we reverted back to the previous version. New version should be coming soon but it depends on production team that are getting busy due to beginning of school year.

**Comment by astrilet** [comment]
Please use English version of admin area for now util this fix is migrated.

**Comment by mhvezina** [comment]
Thank you @astrilet for the info. Will do.

**Comment by astrilet** [comment]
We just deployed version 1-40 that should fix problem described in this issue. I do not have admin access to production, but it worked in test.

**Comment by astrilet** [comment]
I was able to test this issue in production environment after migration of release 1-40. It has been fixed.
