### ISSUE TITLE
change the CARL image logo

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/DMPonline_v4#129]
the image on the footer needs to be changed. A file will be supplied.

**Comment by weiweishi** [comment]
Try the image: https://drive.google.com/open?id=0B63wyUwlUdUST2haMjRzRWVXd2c

**Comment by weiweishi** [comment]
@astrilet the image is now sent to me. Please make the change as part of this release

**Comment by astrilet** [comment]
Changed logo
![screenshot from 2017-08-03 10-44-48](https://user-images.githubusercontent.com/11414991/28933016-d9449ada-7838-11e7-8f20-5be8c8088325.png)

**Comment by weiweishi** [comment]
@astrilet could you please try this logo instead:
https://drive.google.com/open?id=0B63wyUwlUdUScDBMMVNoVDBNdTA

I think the tag line is not readable and probably better to leave without it. 

Thanks!
