### ISSUE TITLE
Footer text does not change from English to French 

### ISSUE THREAD

**Issue by astrilet** [ualbertalib/DMPonline_v4#131]
When switching form English to French language footer text does not change.

**Comment by weiweishi** [comment]
Translation: Web Site Privacy Policy
Politique de confidentialité du site Web (en anglais)
Terms and Conditions change to Terms of Use, and use the term_label text/translation

**Comment by weiweishi** [comment]
@astrilet

**Comment by astrilet** [comment]
![screenshot from 2017-08-03 14-05-43](https://user-images.githubusercontent.com/11414991/28941306-de5c04a6-7854-11e7-8d0c-07a089d85403.png)
![screenshot from 2017-08-03 14-05-32](https://user-images.githubusercontent.com/11414991/28941313-e2da8f16-7854-11e7-92bb-07853100a848.png)
