### ISSUE TITLE
Not able to access "Guidance" menu => throws error

### ISSUE THREAD

**Issue by mhvezina** [ualbertalib/DMPonline_v4#174]
Not able to access "Guidance" menu, for Admins (on the https://assistant.portagenetwork.ca web site). Either with the French or English interface I get the "We're sorry, but something went wrong." error message.

![portage_guidancemenu_yieldserror](https://user-images.githubusercontent.com/10760472/31908829-1ed72952-b806-11e7-8ff4-92bdb9987ccb.png)

**Comment by weiweishi** [comment]
Hi @mhvezina sorry for the late response. The issue is caused by faulty data. I had to remove the test template and guidance group you created, and I've recreated the new test template/guidance group and the access is restored.

**Comment by mhvezina** [comment]
Thanks @weiweishi . Seems to work fine now. Was it "faulty" data I entered myself? Could I reproduce the problem without knowing it?
