### ISSUE TITLE
i18n: My plans, parameters: translation needed

### ISSUE THREAD

**Issue by mhvezina** [ualbertalib/DMPonline_v4#28]
Columns' name are hardcoded(?); Translation needed.
Instructions at the bottom (i.e."The items you selected here will be displayed...") is the content of variable "project_settings_text" in file en.yml. The Iocalized version should be taken instead.

In fact it seems that all the parameters part isn't localized.
![dmpbuilder_myplans_parameters_fr](https://cloud.githubusercontent.com/assets/10760472/7540897/26f6673e-f57f-11e4-8877-133f1da612bf.png)

**Comment by weiweishi** [comment]
also fixed by commit 1fa4ba6429e25f88594f3031042e81f18f7b4f92
