### ISSUE TITLE
i18n: emails need to be translated

### ISSUE THREAD

**Issue by mhvezina** [ualbertalib/DMPonline_v4#29]
DMPonline_v4\app\views\devise\mailer\*.html.erb : text is hardcoded. Additional variables must be added in devise.yml files (and/or maybe we should look at i18n-devise.yml). Then text must be translated.

There is also a small change to make to the header of DMPonline_v4\app\views\devise\confirmations\new.html.erb

**Comment by weiweishi** [comment]
Investigated on the locale files in i18n-devise.yml and installed the gem but it didn't solve the email issues - found more text that are hardcoded in views. will locate these files and contribute back to DCC.

**Comment by weiweishi** [comment]
Found there are some difference between our local translation in config/locales/devise.fr.yml and the locale file in i18n-devise: https://github.com/tigrish/devise-i18n/blob/master/config/locales/fr.yml. @mhvezina could you please review and make changes to devise.fr.yml file if needed. Thanks!

**Comment by weiweishi** [comment]
fixed by commit e3c8275419e6bd0f2ee7

**Comment by mhvezina** [comment]
Yes, I’m working on it. https://github.com/tigrish/devise-i18n/blob/master/config/locales/fr.yml isn’t available anymore but I found other sources to compare.

Marie-Hélène Vézina
Bibliothécaire · Projets de bibliothèque numérique | soutien à la réussite, à la recherche et à l’enseignement
Direction des bibliothèques, Université de Montréal
2910, boul. Édouard-Montpetit, app. 4 (bureau 117), Montréal (Québec)  H3T 1J7
514 343-6111 poste 5225 | marie-helene.vezina@umontreal.ca<mailto:marie-helene.vezina@umontreal.ca>

[image002]

De : Weiwei Shi [mailto:notifications@github.com]
Envoyé : 8 juin 2015 15:12
À : ualbertalib/DMPonline_v4
Cc : Vezina Marie-Helene
Objet : Re: [DMPonline_v4] i18n: emails need to be translated (#29)


Found there are some difference between our local translation in config/locales/devise.fr.yml and the locale file in i18n-devise: https://github.com/tigrish/devise-i18n/blob/master/config/locales/fr.yml. @mhvezina<https://github.com/mhvezina> could you please review and make changes to devise.fr.yml file if needed. Thanks!
