### ISSUE TITLE
i18n: Wrong characters encoding when exporting to PDF

### ISSUE THREAD

**Issue by mhvezina** [ualbertalib/DMPonline_v4#30]
When one is trying to export a plan in PDF, the identification section for the project (project name & identifier, principal investigator, generic description, etc.) appear to be in a different character encoding than the answers to the questions (yellow highlight in the image here after). Also, the labels for the fields of this identification section are not in French as one would expect while exporting from the French interface (green highlight).
![dmpbuilder_pdf_export_fr_problem_char_encodings](https://cloud.githubusercontent.com/assets/10760472/7654151/e3ffcd5c-fae8-11e4-923f-102c1fb00b59.png)

**Comment by mhvezina** [comment]
There is still a small problem with the footer. Body text is ok.

![dmpbuilder_pdf_export_fr_problem_char_encodings_footer](https://cloud.githubusercontent.com/assets/10760472/9450159/07751d6a-4a75-11e5-8a25-7b08c5673745.png)

**Comment by weiweishi** [comment]
This should be fixed now.
