### ISSUE TITLE
i18n: editing a plan; translation needed

### ISSUE THREAD

**Issue by mhvezina** [ualbertalib/DMPonline_v4#31]
Editing a plan: interface. A few text items must be put into variables and translated. see yellow highlight in the image hereafter.
![dmpbuilder_editing_a_plan_interface_fr](https://cloud.githubusercontent.com/assets/10760472/7654573/28a5f0dc-faec-11e4-8681-2b579e822ffb.png)

**Comment by weiweishi** [comment]
Other places have been fixed. 
UAlberta Directives is UAlberta Guidance in English version. Do you want to use a different translation in locale file fr.yml?

**Comment by mhvezina** [comment]
No, "Directives" is ok then.
