### ISSUE TITLE
Exporting plan to docx or csv format not working

### ISSUE THREAD

**Issue by mhvezina** [ualbertalib/DMPonline_v4#32]
I think you are already aware but just in case: trying to export a plan in docx or csv formats isn't working (both test and live instances). I get an error: "The server encountered an internal error or misconfiguration and was unable to complete your request."

Exporting in pdf, html, xml, json and text does however work.

**Comment by mhvezina** [comment]
I still get an error when trying to export in csv.

**Comment by mhvezina** [comment]
2 collaborators reported an error when trying to export plan with text format. I can't reproduce this error on my side though. Do you experience the same problem?

**Comment by umarqasim** [comment]
It is working fine with text format but export in csv format is producing an internal server error

**Comment by weiweishi** [comment]
fixed with an updated gem install

**Comment by weiweishi** [comment]
@mhvezina Addition translations are needed in en.yml file:

        section: "Section"
        question: "Question"
        answer: "Answer"
        selected_options: "Selected option(s)"
        answered_by: "Answered by"
        answered_at: "Answered at"

**Comment by mhvezina** [comment]
section: "Section"
    question: "Question"
    answer: "Réponse" (I assume it's the noun and not the verb "to answer", which one should be translated by "Répondre").
    selected_options: "Option(s) choisie(s)"
    answered_by: "Réponse faite par"   (There is already such a variable in fr.yml, but maybe you are referring to a different section?)
    answered_at: "Réponse faite à" (Not sure for this one, I would need to see it in context....)
