### ISSUE TITLE
color scheme for language toggle 

### ISSUE THREAD

**Issue by mhvezina** [ualbertalib/DMPonline_v4#37]
You might want to change the text color for the link of the language toggle at the top of the page. It's quite difficult to see.... (see attached image). 
![dmpbuilder_languagetoggleunseen](https://cloud.githubusercontent.com/assets/10760472/9444584/a7cbc540-4a55-11e5-9178-e475d5043a98.png)

Also, in my opinion, the green text on the black background in the help in context dialogue (Create a plan => Plan details) is not contrasted enough
![dmpbuilder_greentext_helpincontextuserprofile](https://cloud.githubusercontent.com/assets/10760472/9444585/a7d8f44a-4a55-11e5-889a-f1ea033e0807.png)

**Comment by weiweishi** [comment]
We will need to do an quick interface redesign once we have the portage logo design. Color scheme will definitely be revisited then. I've changed the color of the text for now, to make the testing easier.
