### ISSUE TITLE
i18n: answering questions: description of section isn't translated

### ISSUE THREAD

**Issue by mhvezina** [ualbertalib/DMPonline_v4#39]
When answering questions, it seems that the translated text is not showing for the description of sections. In the example after, it should be : "French - This section addresses data collection......."
![dmpbuilder_answeringquestions_descriptionofsectionnottranslated](https://cloud.githubusercontent.com/assets/10760472/9449470/c2b59f6e-4a70-11e5-94bb-81961f1bdac0.png)

**Comment by weiweishi** [comment]
This is now fixed with the new seed data, where descriptions are included for all sections.
