### ISSUE TITLE
i18n: plan details : fields missing (?) when toggling between languages 

### ISSUE THREAD

**Issue by mhvezina** [ualbertalib/DMPonline_v4#41]
Hum... it seems that, when editing plan details for a given plan, both fields "Plan name" and "Description" are lost(?..or are not displayed?) when toggling from French to English. Other fields are ok. I would expect all metadata to stay the same. here are the screen capture for the same plan (french interface then english interface):
![dmpbuilder_editing_a_plan_togglingbetweenfr enyieldserrors_fr](https://cloud.githubusercontent.com/assets/10760472/9479104/b7abfa80-4b49-11e5-8f23-dc09897a1bb8.png)
![dmpbuilder_editing_a_plan_togglingbetweenfr enyieldserrors_en](https://cloud.githubusercontent.com/assets/10760472/9479103/b7aaf68a-4b49-11e5-8540-7e92bd59b375.png)

**Comment by weiweishi** [comment]
I can't seem to reproduce this issue on UAT server or my own dev machine. Could you please try again and let me know if you continue to experience it. 

Thanks!

**Comment by umarqasim** [comment]
It seems like two separate backend sources are being used. If I edit any
content in the English interface it doesn't reflect in the French interface
and vice versa.

*--*
*Umar Qasim, PhD*
Digital Preservation Officer
2-10N Cameron Library | University of Alberta
Edmonton, Alberta T6G 2J8, Canada
Tel: 780-492-9861 | Fax: 780-492-9243
umar.qasim@ualberta.ca | http://www.umarqasim.ca

**Comment by weiweishi** [comment]
With Umar's help I'm able to reproduce this issue. I'll look into it.

Thanks!

Weiwei

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by weiweishi** [comment]
should be fixed. Please let me know otherwise.
