### ISSUE TITLE
i18n: Unwanted language swap when clicking on button "Create Plan" (top menu) French interface only

### ISSUE THREAD

**Issue by mhvezina** [ualbertalib/DMPonline_v4#42]
When, with the French interface, one clicks on the "Créer un plan" button (in the top menu only, not with the button at the bottom of the introductory text), French interface is lost and the "Crate plan" is displayed in English.
![dmpbuilder_button_createplaninmenutriggerslanguageswap](https://cloud.githubusercontent.com/assets/10760472/9659823/7a166e5c-5220-11e5-9016-96ba36bef86f.png)

**Comment by weiweishi** [comment]
fixed with issue #57
