### ISSUE TITLE
i18n : Licensing and Terms of Use (at the bottom of pages in French interface) points to the English version

### ISSUE THREAD

**Issue by mhvezina** [ualbertalib/DMPonline_v4#43]
Should links in the footer refer only to U of Alberta resources (and not precisely to DMPBuilder resources)? 
They all do except "Licensing and Terms of Use" which refer to the page "https://dmpuat.library.ualberta.ca/terms", in which case the French interface points to the English version of this text instead of the French version.
![dmpbuilder_linkfooterlicenseterms](https://cloud.githubusercontent.com/assets/10760472/9669320/3b0596b4-5254-11e5-994a-6feeb822c81c.png)

However I must say that I thought, at first, that links in this footer were referring to more generic resources and were not specific to the application (i.e. DMPBuilder)... this might be more of a design issue then a i18n issue.... not sure.....

**Comment by weiweishi** [comment]
need Chuck's input on this.

**Comment by mhvezina** [comment]
Since the "Terms" link at the bottom of the DMP Assistant web site (https://assistant.portagenetwork.ca) points to a Portage version of the terms of use (https://assistant.portagenetwork.ca/en/terms) I think this issue isn't relevant anymore and we can close it. I see however that the "Web Site Privacy Policy" link for the website points toward a page at U of Alberta (https://library.ualberta.ca/about-us/policies/privacy-policy) which is probably what we want since the website is hosted at U of Alberta. Am I right? @chumphre

**Comment by chumphre** [comment]
Yes, I agree that the website privacy policy needs to link to the host
institution's policy at the U of A.

**Comment by mhvezina** [comment]
Thank you Chuck, So I guess we can close this issue.
