### ISSUE TITLE
i18n : French Text in Export screen needs adjustments 

### ISSUE THREAD

**Issue by mhvezina** [ualbertalib/DMPonline_v4#44]
French Text in Export screen: needs adjustments

•	Should be “Exporter Mon plan” instead of “Export Mon plan” at top of screen. 
•	Should be “Modèle Portage” instead of “French – Portage Template”).
•	Should be “Information système” [assuming it means system admin info and not administrative info] instead of “Admin details” at bottom of screen. 
![dmpbuilder_frenchexportscreen](https://cloud.githubusercontent.com/assets/10760472/9669517/cc31ca3a-5255-11e5-8cec-204c69cb153c.png)

**Comment by weiweishi** [comment]
Used "Renseignements administratifs" based on another issue #54. Which one I should be using?

**Comment by mhvezina** [comment]
"Renseignements administratifs" is the one to use here.
