### ISSUE TITLE
i18n: "Email can't be blank" is displayed in the French interface

### ISSUE THREAD

**Issue by mhvezina** [ualbertalib/DMPonline_v4#45]
[Problem reported by Pierre Nault @ UQAM]

Both screens "Forgot your password" and "Resend confirmation instructions" display the English text "Email can't be blank" when field email is left blank by error. This variable doesn't seem to be defined in one of our *.yml files. 

Suggested translation : « Email can’t be blank » should be translate into something like « Le champ courriel ne peut être vide ». Should we add this variable in one of our *.yml file?

Also « Email » (on the "Resend confirmation instructions" page) should be translated by « Courriel » (not sure which variable is triggered here... doesn't seem to be the one already defined in fr,yml (fr:helpers:email)).

And last: the "%{resource}" part within the variable fr:errors:messages:not_saved:one defined in devise.fr.yml needs to be translated. Actually it reads like that:

        one: "Une erreur a empêché d’enregistrer ce(tte) %{resource} :"
 ( and same problem with:      
 other: "%{count} erreurs ont empêché d’enregistrer ce(tte) %{resource} :")

What would be the list of other resource? I could provide a translation.

![dmpbuilder_blankemail_frenchscreen_1](https://cloud.githubusercontent.com/assets/10760472/9853527/fa4cc71a-5ad1-11e5-952a-fb90b0677af6.png)
![dmpbuilder_blankemail_frenchscreen_2](https://cloud.githubusercontent.com/assets/10760472/9853528/fa4faf7a-5ad1-11e5-80e2-b10df39602ed.png)

**Comment by weiweishi** [comment]
The error message has to read like this:
Courriel: Le champ courriel ne peut être vide

in order to not breaking other labels unexpectedly. Does it sound okay to you?

**Comment by mhvezina** [comment]
Yes: "Le champ courriel ne peut être vide" is ok.

**Comment by weiweishi** [comment]
It will have a "Courriel: " prefix before the error message for this one.
Does this look okay?
[image: Inline image 1]

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by mhvezina** [comment]
Do you mean:
"Courriel: Le champ courriel ne peut être vide"? It's correct but a little bit redundant. Maybe:
"Courriel: Ce champ ne peut être vide" (= "Email: This field can't be left blank") would be better.... You choose :-)

**Comment by weiweishi** [comment]
Okay. I don't know any French so have no idea what the text really says. So
I will follow your suggestion :)

Thanks!

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca
