### ISSUE TITLE
i18n: Locale isn't following when trying to log in with the French interface and having the wrong username/password

### ISSUE THREAD

**Issue by mhvezina** [ualbertalib/DMPonline_v4#47]
[problem reported by Pierre Lasou @ ULaval]

While choosing the French interface and trying to log in, if either the username or password used is wrong, we are sent back to the log in page in English but the error message is in French. Page should be in French.

![dmpbuilder_logginwithfrenchinterface_wrongpwd](https://cloud.githubusercontent.com/assets/10760472/9855148/84acfa12-5ada-11e5-95d2-64284346f896.png)

**Comment by weiweishi** [comment]
modified the routes to redirect to locale_root_path
