### ISSUE TITLE
Portage template : incomplete questions (French interface)

### ISSUE THREAD

**Issue by mhvezina** [ualbertalib/DMPonline_v4#48]
[reported by Pierre Lasou @ ULaval   and   Natalie Clairoux @ UMontreal

Portage template, French interface

1. Section « Responsabilité et ressource », the following questions should be changed as followed: 
« De quelle façon les responsabilités relatives à **la** gestion des données seront-elles gérées si des changements importants surviennent au sein du personnel qui supervise les données du projet, y compris un changement de chercheur principal? 

I did the correction on the test server (through dashboard) but you may want to report this correction elsewhere as I don't know where is the master version of the template and if other corrections has been added.

2. Section "Conservation" : the 2nd question seems to be incomplete : " Indiquez comment vous vous assurerez que vos données sont prêtes pour la conservation. À prendre en considération: formats de fichier appropriés pour la conservation mais qui préservent l'intégrité des données; anonymisation et dépersonnalisation des **fic** " should be replaced by:

"Indiquez comment vous vous assurerez que vos données sont prêtes pour la conservation. À prendre en considération: formats de fichier appropriés pour la conservation mais qui préservent l'intégrité des données;  anonymisation et dépersonnalisation des fichiers, y compris les fichiers de documentation. " 

I tried to correct that (dashboard on the test server) but couldn't. Looks to me like there is a maximum number of characters allowed to this field.
![dmpbuilder_portagetemplatefrenchsections](https://cloud.githubusercontent.com/assets/10760472/9858996/f7ec345e-5af1-11e5-8145-46af9b5c53e8.png)

**Comment by weiweishi** [comment]
changed the text in the seed file. And change the datatype of the questions to be text instead of string (which limits to 255 characters).
