### ISSUE TITLE
i18n: Portage tempate (French) : Text under "Partage et réutilisation" appears in English

### ISSUE THREAD

**Issue by mhvezina** [ualbertalib/DMPonline_v4#50]
[Reported by Alex Guidon @ UConcordia   and Natalie Clairoux @ UMontreal]

Main Guidance Text (which appears in the “tab”, right under the title of the section) under French section "Partage et réutilisation" is in English. It should be  replaced by the translated text:

"Plusieurs organismes subventionnaires canadiens ont maintenant des politiques exigeant que les données de recherche soient rendues accessibles au moment de la publication des résultats de la recherche ou à l'intérieur d'un délai raisonnable. Si le partage des données contribue à la visibilité et à l'impact de la recherche, il faut aussi tenir compte du souhait des chercheurs de publier un maximum de publications avant de diffuser les données. Également d'importance est le besoin de protéger la vie privée des répondants et de traiter de façon appropriée les données sensibles."

I did replace the text in the Portage template - French on the test server  (admin - dashboard). I don't know if it has to be changed somewhere else (master version of the template somewhere?).

![dmpbuilder_portagetemplate_partage_et_reutilisation](https://cloud.githubusercontent.com/assets/10760472/9859175/1e749cfa-5af3-11e5-84fb-75dacee340e4.JPG)

**Comment by weiweishi** [comment]
should be fixed with a new deployment.
