### ISSUE TITLE
i18n: "Confirm plan details" window when organization is not applicable/not listed. 

### ISSUE THREAD

**Issue by mhvezina** [ualbertalib/DMPonline_v4#51]
[Reported by Pierre Nault 2 UQAM]

Context: French interface: creating a plan (https://dmpuat.library.ualberta.ca/fr/projects/new#) and drop down menu is left to “Veuillez sélectionner un organisme”.

If we click on "Sans objet / non inscrit dans la liste" the Confirm plan details window states "None" instead of the translation "Aucun".

![dmpbuilder_confirmplandetailswindow_none](https://cloud.githubusercontent.com/assets/10760472/9859884/b84fb0e6-5af6-11e5-9102-0851c77cafd9.JPG)

**Comment by weiweishi** [comment]
put in a quick and dirty fix for the javascript strings, need a more elegant solution post-launch.
