### ISSUE TITLE
Button "Update" when editing plan details

### ISSUE THREAD

**Issue by mhvezina** [ualbertalib/DMPonline_v4#55]
[reported by Natalie Clairoux @ UMontreal]

Enhancement request: 
It was suggested that the button "Update" in the Plan details section should be renamed "Save" (or maybe Save/Update ?) as "Update" doesn't quite apply when filing the form for the first time.

![dmpbuilder_buttonupdate_editingplandetails](https://cloud.githubusercontent.com/assets/10760472/9862274/bbfb69f6-5b05-11e5-8d4f-785c0f4ac700.png)

**Comment by weiweishi** [comment]
Made the change. used "Enregistrer" for French version.
