### ISSUE TITLE
Rename "comments" tab to "notes"?

### ISSUE THREAD

**Issue by jasonbrodeur** [ualbertalib/DMPonline_v4#74]
This is content feedback rather than a specific issue, but I've had comments from testers that they are confused about the purpose of the "comments" box. It seems that the use of "comments" as a title makes some believe that this is a feedback mechanism to the DMP Assistant administrators. 
My first thought is that changing this to "notes" would better communicate the purpose of this box.

Thanks,

**Comment by weiweishi** [comment]
@mhvezina 
Could you please send me the translation for Notes. I've made the change in en.yml

**Comment by mhvezina** [comment]
I guess "Annotations" would be ok. I can't see which variable it is however within the en.yml file? I could make the change to fr.yml myself if you wish. I have another small correction to make and maybe other ones....

**Comment by jasonbrodeur** [comment]
Thanks, Weiwei and Marie-Hélène for taking a look at this -- I think making
this change will make the tool more intuitive.

At the same time, however, I don't want to unilaterally force this change
-- if you'd like me to discuss this with the Expert Group first, I'd be
happy to.

Thanks again,

Jay

On Sat, Oct 24, 2015 at 12:09 PM, Marie-Hélène Vézina <
notifications@github.com> wrote:

> I guess "Annotations" would be ok. I can't see which variable it is
> however within the en.yml file? I could make the change to fr.yml myself if
> you wish. I have another small correction to make and maybe other ones....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/DMPonline_v4/issues/74#issuecomment-150830156>
> .
>



-- 
*Jason Brodeur, PhD* | *Manager -- Maps, Data, GIS*
Mills Memorial Library | Room L104B | McMaster University
brodeujj@mcmaster.ca

**Comment by mhvezina** [comment]
Jay, 
I did exchange a few words with Diane Sauvé on this and we both thought "Notes" would be better than "Comments" in that particular context... you can see what the Expert Group has to say on that but I guess on our side we are comfortable with this change.

**Comment by jasonbrodeur** [comment]
Hi Marie-Hélène,

Given that you've run this by Diane already, I am fine to have this change
made without consulting the Expert Group.

Thanks very much for your help,

Jay

On Mon, Oct 26, 2015 at 5:23 PM, Marie-Hélène Vézina <
notifications@github.com> wrote:

> Jay,
> I did exchange a few words with Diane Sauvé on this and we both thought
> "Notes" would be better than "Comments" in that particular context... you
> can see what the Expert Group has to say on that but I guess on our side we
> are comfortable with this change.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/DMPonline_v4/issues/74#issuecomment-151288822>
> .
>



-- 
*Jason Brodeur, PhD* | *Manager -- Maps, Data, GIS*
Mills Memorial Library | Room L104B | McMaster University
brodeujj@mcmaster.ca

**Comment by mhvezina** [comment]
Excellent, let's move forward with this one.

**Comment by weiweishi** [comment]
Great thank you guys @jasonbrodeur @mhvezina 
I'm working on a new release for some bug fixes, @mhvezina do you have more translation fixes you'd like to include?

**Comment by mhvezina** [comment]
Hi Weiwei,

yes I will have some small translation fixes. I also sent an email yesterday to a few colleagues asking them to have a look to the latest  DMP Assistant and report issues (either with the translation and/or the application itself). I will also join the effort.... until when would we be able to submit issues in order to have them included in your next release? (I'm talking about small fixes here I guess). Thanks.

**Comment by weiweishi** [comment]
Hi Marie-Helene
Since we are fixing a significant bug with the organization admin interface
on this release, I'm hoping to have the deployment done in the next day or
two. But we will do at least another round of the release/deployment in the
next two weeks with the all the feedback we hear back. So take your time
for the testing (and THANK YOU SO MUCH for doing it!).

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by weiweishi** [comment]
@mhvezina Could you please provide translations/modification to the following changes in fr.yml:

    add_comment_accordion_label: "Ajouter un annotations"
    comment_accordion_label: "Annotations"

    comments:
      add_comment_label: "Ajouter un annotations"
      add_comment_text: "Veuillez ajouter un annotations"
      comment_label: "Annotations"
      comments_label: "Annotations"
      view_label: "Voir"
      edit_label: "Modifier"
      retract_label: "Supprimer"
      clear_label: "Supprimer"
      commented_by: "Commentaire par :"
      archive_own_comment_question: "Êtes-vous certain de vouloir supprimer ce commentaire?"
      archive_own_comment_button_label: "Supprimer"
      archive_comment_question: "Êtes-vous certain de vouloir supprimer ce commentaire?"
      archive_comment_button_label: "Supprimer"
      clear_by: "Commentaire supprimé par"
      retracted: "Commentaire supprimé par vous"

Thanks

**Comment by mhvezina** [comment]
add_comment_accordion_label: "Ajouter une annotation"
comment_accordion_label: "Annotations"

comments:
  add_comment_label: "Ajouter une annotation"
  add_comment_text: "Veuillez ajouter une annotation"
  comment_label: "Annotations"
  comments_label: "Annotations"
  view_label: "Voir"
  edit_label: "Modifier"
  retract_label: "Supprimer"
  clear_label: "Supprimer"
  commented_by: "Annotation par :"
  archive_own_comment_question: "Êtes-vous certain de vouloir supprimer cette annotation?"
  archive_own_comment_button_label: "Supprimer"
  archive_comment_question: "Êtes-vous certain de vouloir supprimer cette annotation?"
  archive_comment_button_label: "Supprimer"
  clear_by: "Annotation supprimée par"
  retracted: "Annotation supprimée par vous"
