### ISSUE TITLE
i18n: Plan shared: Yes/No is in English in French version

### ISSUE THREAD

**Issue by mhvezina** [ualbertalib/DMPonline_v4#76]
*comment contributed by D. Sauvé*

..Should be Oui/Non in French....
![portage_yes-no_planshared](https://cloud.githubusercontent.com/assets/10760472/10856834/b2991f18-7f20-11e5-8587-d9debca2ea52.png)

**Comment by weiweishi** [comment]
@mhvezina could you give me a translation for "with ** people" for when the option is Yes.

**Comment by mhvezina** [comment]
translation would be:

oui, avec *** personne(s)

or, better:

oui, avec 1 personne    <=singular
oui, avec 5 personnes    <=plural
