### ISSUE TITLE
i18n: Create plan > "Choose a template" not translated in French interface

### ISSUE THREAD

**Issue by mhvezina** [ualbertalib/DMPonline_v4#85]
I can't find an existing variable for "Choose a template" in fr.yml, nor en.yml file....

![portage_choose_template](https://cloud.githubusercontent.com/assets/10760472/10893307/2a0cac70-8176-11e5-9738-aea447a94e92.png)

**Comment by weiweishi** [comment]
Could you please give me the translation for the phrase @mhvezina? Thanks!

**Comment by weiweishi** [comment]
I used "Choisissez un modèle" for now.

**Comment by mhvezina** [comment]
Translation should be: "Choisir un modèle". Thanks.
