### ISSUE TITLE
Web-browser cache-related problems with Portage 

### ISSUE THREAD

**Issue by jasonbrodeur** [ualbertalib/DMPonline_v4#88]
Hello, 

I just tried to browse to the www.portagenetwork.ca site and received the error shown in the image below ("The page you were looking for doesn't exist"). I confirmed that it's a cache problem by trying it again in an incognito window (it worked). 

Do you have any control on the text of this page? If so, it might be worthwhile to suggest that the user tries clearing their cache (after they've confirmed that the address is correct).

Thanks, 

Jay

![portageerror](https://cloud.githubusercontent.com/assets/6332872/12424952/7edfa498-bea0-11e5-8c97-6f37a778eaf9.PNG)

**Comment by jasonbrodeur** [comment]
Closing this issue - further investigation showed this not to be an issue with the cache, but rather something wrong with our administrative account (rdmgmt@mcmaster.ca).

**Comment by weiweishi** [comment]
Could you please let me know what's the issue you encounter with your admin
account? I see it's been deleted? I will set it up with the organization
admin again.

Weiwei

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by jasonbrodeur** [comment]
Hi Weiwei,

I just submitted a new ticket for the issue. That would be great if you
could recreate our account. Any idea why/how it was deleted?

​Thanks,

Jay​


On Tue, Jan 19, 2016 at 12:10 PM, Weiwei Shi <notifications@github.com>
wrote:

> Could you please let me know what's the issue you encounter with your admin
> account? I see it's been deleted? I will set it up with the organization
> admin again.
>
> Weiwei
>
> *Weiwei Shi*
>
> Digital Initiative Applications Librarian
> University of Alberta Libraries
> 2-10L Cameron Library
> Edmonton, Alberta, Canada T6G 2J8
> Phone:(780)492-7802
> Fax: (780)248-1209
> Email: weiwei.shi@ualberta.ca
>
> On Tue, Jan 19, 2016 at 10:05 AM, jasonbrodeur <notifications@github.com>
> wrote:
>
> > Closing this issue - further investigation showed this not to be an issue
> > with the cache, but rather something wrong with our administrative
> account (
> > rdmgmt@mcmaster.ca).
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ualbertalib/DMPonline_v4/issues/88#issuecomment-172919646
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/DMPonline_v4/issues/88#issuecomment-172920977>
> .
>



-- 
*Jason Brodeur, PhD* | *Manager -- Maps, Data, GIS*
Mills Memorial Library | Room L104B | McMaster University
brodeujj@mcmaster.ca

**Comment by weiweishi** [comment]
Sorry I searched for the wrong email address. It was not deleted but not
associated to the right organization. I've replied to your other ticket.
Thanks!

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca
