### ISSUE TITLE
Login problems with admin account 

### ISSUE THREAD

**Issue by jasonbrodeur** [ualbertalib/DMPonline_v4#89]
Resubmitting this after closing the previous ticket. 

We can't log into our administrator account (rdmgmt@mcmaster.ca). After attempting to login, we get the error attached below. This does not seem to be a cache issue, as I've tried on multiple systems and in a private browser. 
![portageerror](https://cloud.githubusercontent.com/assets/6332872/12425997/673d4246-bea5-11e5-8604-657b225fa257.PNG)

**Comment by weiweishi** [comment]
@jasonbrodeur I did some changes to your admin account, please try again and let me know if it solves your issue.

**Comment by jasonbrodeur** [comment]
I can login without issue now -- thanks for resolving this. I also like the
new layout and more straightforward features!

Jay

On Tue, Jan 19, 2016 at 12:15 PM, Weiwei Shi <notifications@github.com>
wrote:

> @jasonbrodeur <https://github.com/jasonbrodeur> I did some changes to
> your admin account, please try again and let me know if it solves your
> issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/DMPonline_v4/issues/89#issuecomment-172922542>
> .
>



-- 
*Jason Brodeur, PhD* | *Manager -- Maps, Data, GIS*
Mills Memorial Library | Room L104B | McMaster University
brodeujj@mcmaster.ca

**Comment by weiweishi** [comment]
Great! Thanks Jay.
