### ISSUE TITLE
Unable to delete a template

### ISSUE THREAD

**Issue by apetryk** [ualbertalib/DMPonline_v4#96]
There's doesn't seem to be a way in the UI for an admin to delete a template - only unpublish it.  See for example "uOttawa Test Template".

**Comment by janeburpee** [comment]
I am having the same problem. We really need to be able to delete the templates. I've created three now in the McGill customized version and I want them gone. Each one is now called blank. 
![screen shot 2016-05-05 at 4 56 01 pm](https://cloud.githubusercontent.com/assets/18724421/15056934/4d43de36-12e2-11e6-95cd-12811435649f.png)

**Comment by weiweishi** [comment]
@janeburpee I've deleted these three template. I've added the delete function to the organization admin and will be deployed in the next release.

**Comment by janeburpee** [comment]
Thank you Wei Wei!

I am certain that adding the delete function will be helpful to others as well.

Jane


________________________________
