### ISSUE TITLE
"Select your organization" should be pre-selected when logged in

### ISSUE THREAD

**Issue by apetryk** [ualbertalib/DMPonline_v4#99]
When creating a new plan, the user is always prompted to select their organization.  This is a redundant step if the user has already specified their institution in their profile.  For such users, the "select your organization" dropdown should either be pre-selected or hidden from the UI.

**Comment by weiweishi** [comment]
The idea of the organization drop down being that a user might want to use
templates from other organizations even they are associated with one. We
can pre-select their home organization to avoid confusion, but I think
there are still value in keeping the option available to the users? What do
you think @apetryk?

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by apetryk** [comment]
I agree: the home organization should be pre-selected as a convenience and to avoid confusion, but the list of all organizations should be visible in case they want to use a different one.

**Comment by weiweishi** [comment]
Seems that we have agreed to keep the home organization selection menu.
